spring:
  application:
    name: itoken-admin
  zipkin:
    base-url: http://127.0.0.1:9411

    
    
server:
  port: 8084
  
management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: "*"
        
eureka:
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:8761/eureka