spring:
  zipkin:
    base-url: http://127.0.0.1:9411
  boot:
    admin:
      client:
        url: http://127.0.0.1:8084
  
eureka:
  instance:
    hostname: 127.0.0.1
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka

mybatis:
  configuration: 
    cache-enabled: true
  type-aliases-package: com.alu.itoken.service.admin.domain
  mapper-location:
    classpath: mapper/*.xml
          
management: 
  endpoint:
    health: 
      show-details: always
  endpoints: 
    web:
      exposure:
        include: health,info  


