spring:
  application:
    name: itoken-web-posts
  thymeleaf:
    cache:  false
    mode: LEGACYHTML5
    encoding: UTF-8
    servlet:
      content-type: text/html
      
 
server:
  port: 8603
 
feign:
  hystrix:
    enabled: true
  

 
 