spring:
  application:
    name: itoken-service-redis
  zipkin:
    base-url: http://127.0.0.1:9411
  boot:
    admin:
      client:
        url: http://127.0.0.1:8084
  redis:
    host: 127.0.0.1
    port: 6379
    timeout: 1000
    poolMaxTotal: 1000
    poolMaxIdle: 500
    poolMaxWait: 500

server:
  port: 8502
feign:
  hystrix:
    enabled: true

eureka:
  instance:
    hostname: 127.0.0.1
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka
management: 
  endpoint:
    health: 
      show-details: always
  endpoints: 
    web:
      exposure:
        include: health,info  
 