spring:
  application:
    name: itoken-zuul
  boot:
    admin:
      client:
        url: http://127.0.0.1:8084
  zipkin:
    base-url: http://127.0.0.1:9411
  

server:
  port: 8767
  
eureka:
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:8761/eureka,http://127.0.0.1:8861/eureka,http://127.0.0.1:8961/eureka
      
zuul:
  routes:
    backend-admin:
      path: /backend/admin/**
      serviceId: itoken-web-admin
    backend-posts:
      path: /backend/posts/**
      serviceId: itoken-web-posts
      